In [1]:
%load_ext autoreload
%autoreload 2

In [10]:
import torch
import kittygrad as kitty

# First test

In [56]:
a = torch.tensor([1, 2, 3.])
b = a
b[1] = 100
a

In [50]:
a = kitty.tensor([1, 2, 3])
b = a
b[1] = 100
a

# Second test

In [75]:
a = torch.tensor([1., 2, 3])
b = a[:2]
b

In [77]:
b[0] = 1000
a

In [89]:
a = kitty.tensor([1., 2, 3])
b = a[:2]
b

In [91]:
b[0] = 1000
a

# Third test

In [97]:
a = torch.tensor([1, 2, 3.])
a.data[0] = 100
a

tensor([100.,   2.,   3.])

In [98]:
a = kitty.tensor([1, 2, 3.])
a.data[0] = 100
a

tensor([100.,   2.,   3.])

# Fourth test

In [101]:
a = torch.tensor([[1, 2, 3], [4, 5, 6.]])
a[:, ::2]

tensor([[1., 3.],
        [4., 6.]])

In [102]:
a = kitty.tensor([[1, 2, 3], [4, 5, 6]])
a[:, ::2]

tensor([[1., 3.],
        [4., 6.]])

# Fifth test

In [104]:
a = torch.tensor([1, 2.])
b = torch.tensor([[0, 0.], [0, 0], [0, 0]])
b[1] = a
b

tensor([[0., 0.],
        [1., 2.],
        [0., 0.]])

In [105]:
a[0] = 1000
b

tensor([[0., 0.],
        [1., 2.],
        [0., 0.]])

In [106]:
a = kitty.tensor([1, 2.])
b = kitty.tensor([[0, 0.], [0, 0], [0, 0]])
b[1] = a
b

tensor([[0., 0.],
        [1., 2.],
        [0., 0.]])

In [107]:
a[0] = 1000
b

tensor([[0., 0.],
        [1., 2.],
        [0., 0.]])